USE Cazuela
INSERT INTO Suppliers (supplier_name,
                       contact_name,
                       address,
                       city,
                       state,
                       country,
                       postal_code,
                       phone_number,
                       email)
VALUES ('ABC Supply Co.',
        'John Smith',
        '123 Main Street',
        'Chicago',
        'IL',
        'USA',
        '60601',
        '(312) 555-0123',
        'jsmith@abcsupply.com'),
       ('XYZ Distribution',
        'Maria Garcia',
        '456 Commerce Ave',
        'Los Angeles',
        'CA',
        'USA',
        '90012',
        '(213) 555-8976',
        'mgarcia@xyzdist.com'),
       ('Global Comics Inc.',
        'Robert Chen',
        '789 Market Blvd',
        'San Francisco',
        'CA',
        'USA',
        '94105',
        '(415) 555-3344',
        'rchen@globalfoods.com'),
       ('Fresh Produce Co.',
        'Sarah Johnson',
        '321 Harvest Road',
        'Seattle',
        'WA',
        'USA',
        '98101',
        '(206) 555-7890',
        'sjohnson@freshproduce.com'),
       ('Mexican Imports Ltd.',
        'Carlos Rodriguez',
        'Av. Revolucion 1234',
        'Mexico City',
        'CDMX',
        'Mexico',
        '06100',
        '(55) 5555-1212',
        'crodriguez@mexicanimports.com'),
       ('European Delicacies',
        'Anna Mueller',
        'Hauptstrasse 42',
        'Berlin',
        'Berlin',
        'Germany',
        '10115',
        '+49 30 555666',
        'amueller@eurodel.de'),
       ('Asian Comics Traders',
        'Lee Ming',
        '45 Trade Street',
        'Singapore',
        'Central Region',
        'Singapore',
        '068813',
        '+65 6789 0123',
        'ming@asianspice.sg'),
       ('Quality Meats Inc.',
        'David Brown',
        '567 Butcher Lane',
        'Dallas',
        'TX',
        'USA',
        '75201',
        '(214) 555-4567',
        'dbrown@qualitymeats.com'),
       ('Organic Farms Co-op',
        'Lisa Green',
        '890 Natural Way',
        'Portland',
        'OR',
        'USA',
        '97201',
        '(503) 555-9876',
        'lgreen@organicfarms.org'),
       ('Spice World Trading',
        'Raj Patel',
        '123 Flavor Street',
        'Mumbai',
        'Maharashtra',
        'India',
        '400001',
        '+91 22 5555 0000',
        'rpatel@spiceworld.in');